sudo: true
language: cpp
dist: trusty

matrix:
  include:

  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-8
      - FLAGS=-std=c++17
      - BUILD_TYPE=Debug
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'ppa:mhier/libboost-latest'
        packages:
          - libssl-dev
          - boost1.67
          - g++-8

  - os: linux
    compiler: clang
    env:
      - COMPILER=clang++-6.0
      - FLAGS="-std=c++17 -stdlib=libstdc++"
      - BUILD_TYPE=Debug
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
          - sourceline: 'ppa:mhier/libboost-latest'
        packages:
          - libssl-dev
          - boost1.67
          - clang++-6.0
          - g++-8

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential cmake libboost-all-dev miniupnpc libunbound-dev graphviz doxygen libunwind8-dev pkg-config libssl-dev libcurl4-openssl-dev libgtest-dev libreadline-dev libzmq3-dev libsodium-dev libhidapi-dev libhidapi-libusb0
  - git clone --recurse-submodules https://github.com/monero-project/monero.git && cd monero && make  

install:
  - uname -a
  - if [[ "${COMPILER}" != "" ]]; then $COMPILER --version; fi
  - OS=`uname -s`
  - |
    wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.sh
    chmod +x ./cmake-3.11.4-Linux-x86_64.sh
    sudo ./cmake-3.11.4-Linux-x86_64.sh --prefix=. --exclude-subdir --skip-license
    ./bin/cmake --version

script:
  - mkdir build && cd build
  - |
    ../bin/cmake  -DCMAKE_CXX_FLAGS="${FLAGS}" -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
    make 
