sudo: true
language: cpp
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-6.0
    - sourceline: 'ppa:mhier/libboost-latest'
    packages:
    - gcc-8
    - g++-8
    - clang++-6.0
    - libboost1.67-all-dev
    - libssl-dev
    - miniupnpc 
    - libunbound-dev 
    - doxygen 
    - libunwind8-dev 
    - pkg-config l
    - libcurl4-openssl-dev 
    - libgtest-dev 
    - libreadline-dev 
    - libzmq3-dev 
    - libsodium-dev 
    - libhidapi-dev 
    - libhidapi-libusb0

matrix:
  include:

  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-8
      - FLAGS=-std=c++17
      - BUILD_TYPE=Debug

before_install:
  - sudo apt-get update

install:
  - uname -a
  - if [[ "${COMPILER}" != "" ]]; then $COMPILER --version; fi
  - OS=`uname -s`
  - |
    wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.sh
    chmod +x ./cmake-3.11.4-Linux-x86_64.sh
    sudo ./cmake-3.11.4-Linux-x86_64.sh --prefix=. --exclude-subdir --skip-license
    ./bin/cmake --version
  - git clone --recurse-submodules https://github.com/monero-project/monero.git && cd monero && USE_SINGLE_BUILDDIR=1 make  

script:
  - mkdir build && cd build
  - |
    ../bin/cmake  -DCMAKE_CXX_FLAGS="${FLAGS}" -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
    make 
