version: 2

jobs:
  build:
    docker:
      - image: "ubuntu:18.04"
    steps:
      - checkout
      - run:
          name: Installing GCC, git and cmake
          command: |
              apt-get update 
              apt-get install -yqq --no-install-recommends git cmake gcc g++ \
                 libssl-dev libsodium-dev libzmq3-dev pkg-config libpgm-dev \
                 libboost-program-options-dev libboost-chrono-dev libboost-filesystem-dev \
                 libboost-serialization-dev libboost-regex-dev  libboost-locale-dev \
                 libboost-thread-dev libboost-fiber-dev \
                 libjsoncpp-dev uuid-dev

      - run:
          name: Get Last monero commit hash 
          command: |
              export MONERO_COMMIT=`git ls-remote https://github.com/monero-project/monero HEAD | head -n1 | awk '{print $1;}'`
              echo $MONERO_COMMIT > ~/monerocommit
              cat ~/monerocommit
      - restore_cache:
          key: monero-{{ checksum "~/monerocommit" }}
      - run:
          name: Compile Monero
          command: |
                  if [ ! -d "monero" ]; then 
                  git clone --recurse-submodules https://github.com/monero-project/monero.git 
                  cd monero
                  USE_SINGLE_BUILDDIR=1 make release -j 1 
                  cd ..
                  fi
      - save_cache: 
          key: monero-{{ checksum "~/monerocommit" }}
          paths: 
            - "monero"
      - run:
          name: Get submodules
          command: 'git submodule update --init --recursive'
      - run:
          name: Creating Build Files 
          command: 'cmake -DMONERO_DIR=/root/project/monero -DBUILD_TESTS=ON -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build -- -j 2'
      - run:
          name: Run tests
          command: 'cd build && make test'
